<?php function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,"UTF-8");} ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Todd Upshaw - Personal Budget Tracker</title>
<style>
body{font-family:Arial;background:#f3f4f6;margin:0;color:#1f2937}header{background:#1f2937;color:#fff;text-align:center;padding:28px}.container{width:92%;max-width:1200px;margin:25px auto}.section,.card{background:#fff;padding:22px;margin-bottom:22px;border-radius:8px;box-shadow:0 2px 8px #0001}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.amount{font-size:26px;font-weight:bold}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{font-weight:bold;display:block;margin-bottom:5px}input,select,textarea{width:100%;padding:10px;box-sizing:border-box}textarea{min-height:80px}button,.btn{border:0;border-radius:5px;padding:9px 13px;color:#fff;text-decoration:none;cursor:pointer}.blue{background:#2563eb}.green{background:#059669}.orange{background:#f59e0b}.red{background:#dc2626}.gray{background:#64748b}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}th{background:#e5e7eb}.message{background:#dcfce7;padding:12px;margin-bottom:15px}.error{background:#fee2e2;padding:12px;margin-bottom:15px}.edit-box{border:2px solid #f59e0b}.actions{display:flex;gap:5px;flex-wrap:wrap}.progress{height:18px;background:#ddd;border-radius:10px;overflow:hidden}.progress-bar{height:100%;background:#2563eb}@media(max-width:800px){.cards,.form-grid{grid-template-columns:1fr}table{display:block;overflow-x:auto}}
</style></head><body>
<header><h1>Personal Budget Tracking System</h1><p>Student: Todd Upshaw</p><p>SDC310L - Week 4 MVC</p></header><div class="container">
<?php if($data["message"]): ?><div class="message"><?=e($data["message"])?></div><?php endif; ?>
<?php if($data["error"]): ?><div class="error"><strong>Error:</strong> <?=e($data["error"])?></div><?php endif; ?>
<div class="cards"><div class="card"><h3>Total Income</h3><div class="amount">$<?=number_format($data["summary"]["income"],2)?></div></div><div class="card"><h3>Total Expenses</h3><div class="amount">$<?=number_format($data["summary"]["expenses"],2)?></div></div><div class="card"><h3>Balance</h3><div class="amount">$<?=number_format($data["summary"]["balance"],2)?></div></div></div>
<?php if($data["editTransaction"]): $t=$data["editTransaction"]; ?><div class="section edit-box"><h2>Edit Transaction</h2><form method="post"><input type="hidden" name="action" value="update_transaction"><input type="hidden" name="transaction_id" value="<?=e($t["transaction_id"])?>"><div class="form-grid"><div><label>Type</label><select name="transaction_type"><option <?= $t["transaction_type"]==="Income"?"selected":"" ?>>Income</option><option <?= $t["transaction_type"]==="Expense"?"selected":"" ?>>Expense</option></select></div><div><label>Amount</label><input type="number" step="0.01" name="amount" value="<?=e($t["amount"])?>" required></div><div><label>Category</label><input name="category" value="<?=e($t["category"])?>" required></div><div><label>Date</label><input type="date" name="transaction_date" value="<?=e($t["transaction_date"])?>" required></div><div style="grid-column:1/-1"><label>Description</label><textarea name="description"><?=e($t["description"])?></textarea></div></div><br><button class="green">Update Transaction</button> <a class="btn gray" href="index.php">Cancel</a></form></div><?php endif; ?>
<div class="section"><h2>Create Transaction</h2><form method="post"><input type="hidden" name="action" value="create_transaction"><div class="form-grid"><div><label>Type</label><select name="transaction_type"><option>Income</option><option>Expense</option></select></div><div><label>Amount</label><input type="number" step="0.01" name="amount" required></div><div><label>Category</label><input name="category" required></div><div><label>Date</label><input type="date" name="transaction_date" required></div><div style="grid-column:1/-1"><label>Description</label><textarea name="description"></textarea></div></div><br><button class="blue">Add Transaction</button></form></div>
<div class="section"><h2>Transactions</h2><table><tr><th>ID</th><th>Type</th><th>Amount</th><th>Category</th><th>Date</th><th>Description</th><th>Actions</th></tr><?php foreach($data["transactions"] as $t): ?><tr><td><?=e($t["transaction_id"])?></td><td><?=e($t["transaction_type"])?></td><td>$<?=number_format($t["amount"],2)?></td><td><?=e($t["category"])?></td><td><?=e($t["transaction_date"])?></td><td><?=e($t["description"])?></td><td><a class="btn orange" href="?edit=<?=e($t["transaction_id"])?>">Edit</a> <form method="post" style="display:inline"><input type="hidden" name="action" value="delete_transaction"><input type="hidden" name="transaction_id" value="<?=e($t["transaction_id"])?>"><button class="red" onclick="return confirm('Delete this transaction?')">Delete</button></form></td></tr><?php endforeach; ?></table></div>
<div class="section"><h2>Create Savings Goal</h2><form method="post"><input type="hidden" name="action" value="create_goal"><div class="form-grid"><div><label>Goal Name</label><input name="goal_name" required></div><div><label>Target Amount</label><input type="number" step="0.01" name="target_amount" required></div><div><label>Current Amount</label><input type="number" step="0.01" name="current_amount" value="0" required></div><div><label>Target Date</label><input type="date" name="target_date" required></div></div><br><button class="blue">Add Savings Goal</button></form></div>
<div class="section"><h2>Savings Goals</h2><table><tr><th>Goal</th><th>Target</th><th>Current</th><th>Progress</th><th>Date</th><th>Action</th></tr><?php foreach($data["goals"] as $g): $p=$g["target_amount"]>0?min(100,($g["current_amount"]/$g["target_amount"])*100):0; ?><tr><td><?=e($g["goal_name"])?></td><td>$<?=number_format($g["target_amount"],2)?></td><td>$<?=number_format($g["current_amount"],2)?></td><td><div class="progress"><div class="progress-bar" style="width:<?=$p?>%"></div></div><?=number_format($p,1)?>%</td><td><?=e($g["target_date"])?></td><td><form method="post"><input type="hidden" name="action" value="delete_goal"><input type="hidden" name="goal_id" value="<?=e($g["goal_id"])?>"><button class="red" onclick="return confirm('Delete this savings goal?')">Delete</button></form></td></tr><?php endforeach; ?></table></div>
</div></body></html>
